name: Persistent runner workflow
on:
  workflow_call:
permissions:
  contents: read
jobs:
  execute:
    runs-on: [self-hosted, sdirk3-wrf]
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
